id: oi-wiki:dp/dp-of-dp_2
name: DP of DP
solution:
  cpp: docs/dp/code/dp-of-dp/dp-of-dp_2.cpp
target:
- 'test'
testcases:
  answer: docs/dp/examples/dp-of-dp/dp-of-dp_2.ans
  input: docs/dp/examples/dp-of-dp/dp-of-dp_2.in
version: 1000
