id: oi-wiki:dp/dp-of-dp_1
name: DP of DP
solution:
  cpp: docs/dp/code/dp-of-dp/dp-of-dp_1.cpp
target:
- 'test'
testcases:
  answer: docs/dp/examples/dp-of-dp/dp-of-dp_1.ans
  input: docs/dp/examples/dp-of-dp/dp-of-dp_1.in
version: 1000
